spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      database: "microservices"
      username: root
      password: mongodb
  jackson:
    default-property-inclusion: NON_NULL
